--Q1. What is the total revenue generated by male vs. female customers?

SELECT gender, SUM(purchase_usd) AS revenue 
FROM customer
GROUP BY gender;


--Q2. Which customers used a discount but still spent more than the average purchase amount? 

SELECT customer_id, purchase_usd
FROM customer
WHERE discount_applied = 'Yes' AND 
purchase_usd >= (SELECT AVG(purchase_usd) FROM customer)


-- Q3. Which are the top 5 products with the highest average review rating?

SELECT TOP 5 item_purchased, ROUND(AVG(review_rating),2) AS "Average_Product_Rating"
FROM customer
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC


--Q4. Compare the average Purchase Amounts between Standard and Express Shipping.  

SELECT shipping_type, AVG(purchase_usd) AS 'Avg Purchase'
FROM customer
WHERE shipping_type IN ('Standard', 'Express')
GROUP BY shipping_type


--Q5. Do subscribed customers spend more? Compare average spend and total revenue 
--between subscribers and non-subscribers.

SELECT subscription_status, COUNT(CUSTOMER_id) AS 'Total Customer',
ROUND(AVG(purchase_usd),2) AS 'AVG Spend',
ROUND(SUM(purchase_usd),2) AS 'Total Revenue'
FROM customer
GROUP BY subscription_status
ORDER BY [Total Revenue], [AVG Spend] DESC


--Q6. Which 5 products have the highest percentage of purchases with discounts applied?

SELECT item_purchased,
CAST(ROUND(100.0 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) / COUNT(*),2) AS DECIMAL(5,2)) AS [Discount Rate]
FROM dbo.Customer
GROUP BY item_purchased
ORDER BY [Discount Rate] DESC
OFFSET 0 ROWS FETCH NEXT 5 ROWS ONLY;


--Q7. Segment customers into New, Returning, and Loyal based on their total 
--number of previous purchases, and show the count of each segment. 

WITH customer_type AS (
    SELECT 
        customer_id, 
        previous_purchases,
        CASE 
            WHEN previous_purchases = 1 THEN 'New'
            WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
            ELSE 'Loyal'
        END AS [Customer Segment]
    FROM dbo.Customer
)
SELECT [Customer Segment], COUNT(*) AS [Number of Customers]
FROM customer_type
GROUP BY [Customer Segment];


--Q8. What are the top 3 most purchased products within each category? 

WITH item_count AS (
    SELECT category, item_purchased, COUNT(customer_id) AS Total_orders
    FROM dbo.Customer
    GROUP BY category, item_purchased
),
ranked_items AS (
    SELECT category, item_purchased, Total_orders,
        ROW_NUMBER() OVER (PARTITION BY category ORDER BY Total_orders DESC) AS item_rank
    FROM item_count
)
SELECT 
    item_rank, category, item_purchased, Total_orders
FROM ranked_items;


--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe? 

SELECT 
    subscription_status,
    COUNT(customer_id) AS [Repeat Buyers]
FROM dbo.Customer
WHERE previous_purchases > 5
GROUP BY subscription_status;


--Q10. What is the revenue contribution of each age group? 

SELECT 
    age_group,
    SUM(purchase_usd) AS total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue desc;